### ISSUE TITLE
issues with updating postgres container

### ISSUE THREAD

**Issue by llsmith05** [kobotoolbox/kobo-docker#100]
I'm updating a fairly out of date (at commit b64ef86 - still running psql container if that matters) server with docker-compose and keep losing my old postgres data. I did the following:
`docker-compose down`
Pulled latest from git and updated all envfiles
`docker-compose pull`
deleted log/rabbitmq because it was causing the container startup to fail with a permissions issue
`docker-compose up -d`

 Here's what i'm seeing in the logs (I'm new-ish to docker and still figuring some of these things out, so bear with me!)
First hints of an issue is when the pg_dump attempt fails:

> postgres_1        | Creating `pg_restore`-compatible, compressed backup of the old `kobotoolbox` database.
> postgres_1        | pg_dump: [archiver (db)] query failed: ERROR:  could not access file "$libdir/postgis-2.1": No such file or directory
> postgres_1        | pg_dump: [archiver (db)] query was: SELECT a.attnum, a.attname, a.atttypmod, a.attstattarget, a.attstorage, t.typstorage, a.attnotnull, a.atthasdef, a.attisdropped, a.attlen, a.attalign, a.attislocal, pg_catalog.format_type(t.oid,a.atttypmod) AS atttypname, array_to_string(a.attoptions, ', ') AS attoptions, CASE WHEN a.attcollation <> t.typcollation THEN a.attcollation ELSE 0 END AS attcollation, pg_catalog.array_to_string(ARRAY(SELECT pg_catalog.quote_ident(option_name) || ' ' || pg_catalog.quote_literal(option_value) FROM pg_catalog.pg_options_to_table(attfdwoptions) ORDER BY option_name), E',
> postgres_1        |     ') AS attfdwoptions FROM pg_catalog.pg_attribute a LEFT JOIN pg_catalog.pg_type t ON a.atttypid = t.oid WHERE a.attrelid = '18656'::pg_catalog.oid AND a.attnum > 0::pg_catalog.int2 ORDER BY a.attrelid, a.attnum
> postgres_1        | *** /etc/my_init.d/10_init_postgres.bash failed with status 1

It reattempts init_postgres.bash, and this time around at the version check I see
`postgres_1        | cat: /srv/db/PG_VERSION: No such file or directory`
so I'm assuming it's skipping the rest of the upgrade process, because the next error I get is:

`postgres_1        | postgres cannot access the server configuration file "/etc/postgresql/9.4/main/postgresql.conf": No such file or directory`

The container fails a few times, exits, recreates, fails, etc. If I take everything down with `docker-compose down` and bring it up again, it all starts up just fine, but... my old db is gone and the pg_dump backup is empty (obviously). Thoughts?

**Comment by esmail** [comment]
So sorry for the trouble. Looks like the issue is that your DB was created while we were using PostGIS 2.1, which isn't compatible with this migration script since there aren't Ubuntu 16.04/Xenial `apt` packages for it. I'll put in a check to avoid getting the script started with an incompatible PostGIS version going forward.

In the process of this failure, your DB was [moved](https://github.com/kobotoolbox/kobo-docker/blob/2027c909b05d8585b195b8086e8e2e9659b96754/base_images/postgres/init_postgres.bash#L26-L31) from `/srv/db`, which is mapped to `.vols/db` on your host, to a directory that only exists within the container, `/srv/db_9.3`. That being a container-only directory, it's at risk of being lost if you delete the container it's in, so hopefully you haven't done so already with `docker rm ...` or `docker-compose rm ...` and please don't 'til your DB is recovered.

If that container is still your most recent `postgres` container, you can go into it with `docker-compose up -d postgres && exec postgres bash` and verify there are database files in `/srv/db_9.3`. If the directory is there, you can back up and remove the `/srv/db` directory (should be empty but just to be safe) e.g. by moving it into `/srv/backups` and moving `/srv/db_9.3` in its place.  At this point your DB files will at least be available on your host for you to back up easily.

If `/srv/db_9.3` is not present in your latest `postgres` container, the container we're looking for with that directory might still be among those listed when executing `docker ps -a`. Any old containers will likely only be identified by unrecognisable container and image hashes, so I'd check the Docker storage directory directly. Start by identifying your Docker root directory with `docker info | grep 'Docker Root Dir'` and searching for a `db_9.3` directory within it with e.g `find ${YOUR_DOCKER_ROOT_DIR} -name db_9.3`. Back up a copy of the found directory(s).

Let me know how this goes and we can proceed from there.

**Comment by llsmith05** [comment]
Thanks, that makes sense why it's happening. I wasn't able to find the old DB, but I'm on AWS and took a snapshot, so I restored an image. I made a backup of the DB with both pg_dump and copying the full /srv/db directory to a safe place outside the psql container. Any advice on getting the update to work? Just update the containers, let it lose the DB, and pg_restore the backup? Thank you, your help (and development work) is much appreciated!

**Comment by esmail** [comment]
So sorry to hear you weren't able to retrieve the container with your DB, but I'm glad you had a backup; I hope your snapshot isn't too far behind.

To restore, you'll want to pull the latest `kobo-docker` code and `postgres` image and run your `pg_restore` manually in a `postgres` container without any interference from the initialization scripts. I'd recommend putting your DB dump into the `kobo-docker/backups/postgres` directory, where it'll be [accessible](https://github.com/kobotoolbox/kobo-docker/blob/2027c909b05d8585b195b8086e8e2e9659b96754/docker-compose.server.yml#L23) inside `postgres` containers, then running your commands in a temporary container with `docker-compose run --rm postgres bash`. Let me know how it goes.

Also, please see the warning at the top of the README about preserving your user-uploaded content with older `kobo-docker` installations and let me know if you have any questions about that process.

**Comment by llsmith05** [comment]
Thanks, this is helpful. Now my newbie status to docker is going to show through: if I bring up a shell in the latest postgres container with `docker-compose run --rm postgres bash`, I am unable to run pg_restore or even psql, and it looks like the server is not running. Shouldn't running the container initialize the DB, or do I have to initialize and configure it in order to run the restore?

For kicks, I tried running the restore in the fully initialized kobodocker postgres container via `docker-compose exec -it kobodocker_postgres_1 bash` and it ran, but vomited out a million errors and doesn't seem to have restored anything.

**Comment by esmail** [comment]
No worries. The issue with not being able to run `psql`, etc. is that the `postgres` server daemon isn't automatically run since you're just starting it up running `bash`. To see how it's usually run, check [`/etc/service/postgres/run`](https://github.com/kobotoolbox/kobo-docker/blob/2027c909b05d8585b195b8086e8e2e9659b96754/base_images/postgres/run_postgres), but maybe skip the `exec`.

**Comment by llsmith05** [comment]
Ok, that makes sense. I got a little education on the ins and outs of docker this week. I was able to successfully restore my database to updated containers and all is looking pretty good. Thanks for the help! Much appreciated.
