### ISSUE TITLE
Documentation: How to update containers.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#11]
Document how to update already running containers with newer images or updated configuration settings.

**Comment by esmail** [comment]
It should suffice to build/pull the newer images (i.e. `docker-compose build; docker-compose pull`) or update the environment variables in your `envfile` and/or `docker-compose.yml`, then stop the container(s) to be updated (e.g. `docker-compose stop kpi`), then bring the container(s) up again (e.g. `docker-compose up -d kpi`).

It's likely safe to do this with any container other than `psql` (which might also be safe).

**Comment by jnm** [comment]
Since [`/srv/db` is a volume mapped to outside the container](https://github.com/kobotoolbox/kobo-docker/blob/docker_local/docker-compose.server.yml#L17) and the Postgres daemon [runs with the `-D /srv/db` argument](https://github.com/kobotoolbox/kobo-docker/blob/docker_local/base_images/psql/Dockerfile#L15), it should be safe to stop and even remove the psql container. @Esmail, should we instruct people to `docker-compose rm`? Certain configuration changes, e.g. modifying the volume mappings, require removing the container. The warning from `docker-compose` is pretty clear, but I wouldn't underestimate people's ability to ignore it:
```WARNING: Service "kobocat" is using volume "/srv/src/kobocat" from the previous container. Host mapping "/tmp/foo" has no effect. Remove the existing containers (with `docker-compose rm kobocat`) to use the host volume mapping.```
Other than that, we could advise people to watch for `Recreating [container name]` in the output of `docker-compose up -d` as indicating a successful update.

**Comment by esmail** [comment]
Oh, so @jnm you're recommending `docker-compose rm` so they don't keep defunct, no longer to be used containers taking up space on their hard drives?

**Comment by jnm** [comment]
Actually, I didn't think of that. My understanding is that if:

1. User modifies volume configuration, e.g. edits https://github.com/kobotoolbox/kobo-docker/blob/docker_local/docker-compose.local.yml#L38;
1. User does `docker-compose stop ...` followed by `docker-compose up ...`;
1. User gets warning that their changes to the volume configuration have *not* taken effect;
1. User doesn't see / understand or ignores warning;

then sadness results :cry:. To keep it :100:, the user would have to `docker-compose stop ...`, `docker-compose rm ...`, and finally `docker-compose up ...`, so maybe we should include that in the catch-all instructions, as opposed to trying to distinguish between the circumstances that require container removal versus those that don't.

**Comment by esmail** [comment]
Got it :) Sounds like a plan.

**Comment by noliveleger** [comment]
@jnm: Still valid?

**Comment by jnm** [comment]
I think we can close this.
