### ISSUE TITLE
`KOBO_POSTGRES_DB_NAME` missing from backup script

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#118]
See https://github.com/kobotoolbox/kobo-docker/blob/532e808706b61deff269dfdfc71781e0086f6124/base_images/postgres/backup_postgres.bash#L6

**Comment by YKolokoltsev** [comment]
I got the same error. 

DESCRIPTION:
The recipe to backup a PostgreSQL is the following
docker exec -it kobodocker_postgres_1 /srv/backup_postgres.bash

However, after the clean installation of KoboDocker the backup_postgres.bash returns an empty database. It happens because of the empty KOBO_POSTGRES_DB_NAME variable used by the script.

SOLUTION 1:
To resolve this bug locally it is sufficient to append into the files envfile.local.txt and envfile.server.txt the next line:
KOBO_POSTGRES_DB_NAME=kobotoolbox

After the docker-compose restart, the backup_postgres.bash will work propertly.

PROBABLY SOLUTION TO CLOSE AN ISSUE
However, it seems that this is an ad-hook solution, and this variable needs to be hardcooded inside of the backup_postgres.bash script, as it is already done in the init_postgres.bash.

**Comment by noliveleger** [comment]
Not the case anymore. The backup mechanism has changed since this issue was opened. 
See `https://github.com/kobotoolbox/kobo-docker/#backups`
