### ISSUE TITLE
Postgres User/Password change to secure auth from external sources

### ISSUE THREAD

**Issue by janknobloch** [kobotoolbox/kobo-docker#161]
Hey all,
im working on accessibility for mongo/postgres from outside the docker environment for further analytics.

For mongo everything seems to work fine: (steps for others to reproduce in case u need it..)
1. start kobo
2. login to mongo container -> add user/password
3. exit mongo container
4. change base-images/mongo and add --auth
5. edit docker-compose.yml to use base-image
6. modify envfiles/kobocat.txt -> change mongo user/password

However for postgre: kobocat.txt nor kpi.txt does include a User **+** Password variables for postgresql.
Therefore my kpi_1 container fails as its still trying to connect user/password combination (kobo/kobo)

`kpi_1             | django.db.utils.OperationalError: FATAL:  password authentication failed for user "kobo"`

Can someone point me in the direction where to update the user/password combinations to make sure my kpi_1 and kobocat_1 container will adapt the needed changes?

Best
Jan

**Comment by noliveleger** [comment]
@janknobloch: You may want to give a try to `kobo-install`. 

Please read the [readme](https://github.com/kobotoolbox/kobo-docker/#upgrading-from-an-old-version-of-kobo-docker-before-to-march-2019) especially if you have an older version and want to install on top of it.

Otherwise, `kobo-docker` does provide such information in `databases.txt` now. 
Be aware that the structure of docker containers changed a lot since March 2019.
