### ISSUE TITLE
RabbitMQ and Redis timeout

### ISSUE THREAD

**Issue by jd-alexander** [kobotoolbox/kobo-docker#220]
I am trying to get kobo-docker working on a digital ocean droplet but I keep having issues with RabbitMQ & Redis
```
kpi_1             |
kpi_1             | *** Killing all processes...
kpi_1             | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
kpi_1             | *** Running /etc/my_init.d/01_wait_for_rabbit.bash...
kpi_1             | Waiting for container `rabbit`.
kpi_1             | 2018/12/22 02:46:02 Waiting for host: tcp://rabbit.kobo.private:5672
kpi_1             | 2018/12/22 02:46:42 Timeout after 40s waiting on dependencies to become available: [tcp://rabbit.kobo.private:5672]
kpi_1             | *** /etc/my_init.d/01_wait_for_rabbit.bash failed with status 1
```
```
enketo_express_1  | 02:44:47 0|enketo  | Error: Redis connection to redis-main.kobo.private:6379 failed - connect ETIMEDOUT 159.65.125.27:6379
enketo_express_1  | 02:44:47 0|enketo  |   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
enketo_express_1  | 02:44:47 0|enketo  | Error: Redis connection to redis-main.kobo.private:6379 failed - connect ETIMEDOUT 159.65.125.27:637
```
Is there a way I can figure out what is causing this to occur? Any thoughts on if the timeout needs to be increased of there could be some form of configuration that's throwing things off. Thanks for the help.

**Comment by szabozoltan69** [comment]
A have the same problem.

**Comment by noliveleger** [comment]
Hi there, 
@jd-alexander, @szabozoltan69. 
You should give `kobo-install` a try. It's a beta and still needs improvement but may help to create your configuration files and run `KoBo` easily.

**Comment by szabozoltan69** [comment]
Hi,
  I used kobo-install. Now the Ubuntu version (as **standalone workstation)** started fine in the cloud also. But the server version gets into infinite loop with waiting to rabbit (in case of Centos) and some similar "no proper backend communication in case of Ubuntu.

**Comment by noliveleger** [comment]
Did you use `advanced options`?
`kobo-install` has been tested on `ubuntu server 16.04 LTS` so it should be fine. 
`kobo-install` uses the IP of the network interface to communicate between frontend and backend. When it builds the configuration files, docker containers are not started yet, so it's not possible to get their `docker` ip.  Moreover, `backend` could be a separate server, so using the docker internal network couldn't work in that case.

Do you use a firewall on this server? If yes, you may need to open ports from local traffic. 
Otherwise, you can try to change manually the `extra hosts` in `docker-compose.frontend.override.yml`.

You should see something like this (several times) 
```
      - postgres.kobo.private:10.201.x.x
      - mongo.kobo.private:10.201.x.x
      - redis-main.kobo.private:10.201.x.x
      - rabbit.kobo.private:10.201.x.x
      - redis-cache.kobo.private:10.201.x.x
```
Replace the VM ip by `docker0` ip address, something like `172.18.x.1`
```
      - postgres.kobo.private:172.18.x.1
      - mongo.kobo.private:172.18.x.1
      - redis-main.kobo.private:172.18.x.1
      - rabbit.kobo.private:172.18.x.1
      - redis-cache.kobo.private:172.18.x.1
```

Obviously, you will have to adapt `x` to your environment. 
You can then restart frontend containers with this command (within `kobo-docker` directory) 
`docker-compose -f docker-compose.frontend.yml -f docker-compose.frontend.override.yml up -d`

**Comment by noliveleger** [comment]
@szabozoltan69 yes, `kobo-install` always rewrites config files that's why I gave you the command `kobo-install` runs. 
Don't try to run `python run.py` after having modified the `docker-compose.frontend.override.yml`. Run the command I gave you earlier within `kobo-docker` folder and see if it helps.

**Comment by szabozoltan69** [comment]
Thank you, it helped.
