### ISSUE TITLE
Backup / Restore more details

### ISSUE THREAD

**Issue by localsnet** [kobotoolbox/kobo-docker#258]
Hello.
I've ran ok kobotoolbox. I made manually all databases backups from your README.
If I loose containers but have previously commited (docker commit kobo*) all kobo containers with that backups, how correctly I can restore and run all services with my data?
@noliveleger  can you help me please?

**Comment by noliveleger** [comment]
@localsnet You have more chances to get some help from the community forum.
Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. https://community.kobotoolbox.org/c/kobo-install.

You can try this though:

- Copy your backup files in `kobo-docker/backups/<service>` 
- Run these commands: https://github.com/kobotoolbox/kobo-docker/#restore

You may need to drop PostgreSQL database and redis dump before restoring your backup.
