### ISSUE TITLE
Port over `kobocat/onadata/apps/survey_report/`.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#53]
Give KPI direct access to Mongo and use `formpack` to generate reports.

**Comment by jeverling** [comment]
Maybe now would be the perfect time to get rid of MongoDB and use a Django 1.9 `JSONField` instead? https://docs.djangoproject.com/ja/1.9/ref/contrib/postgres/fields/#jsonfield
Django 1.9 added a `JSONField` for PostgreSQL ≥ 9.4 that uses the new `jsonb` datatype. This datatype can be indexed and queried. Django 1.9 supports querying the `JSON` stored in the `jsonb` column.
I think it would be a nice improvement to KoBo to get rid of the need to mirror the data into MongoDB. It would not only make setup and maintenance (backups) easier (since PostgreSQL is used anyway) but it would also allow to work with the data using Django (or even querying PostgreSQL directly) without having to query MongoDB.

**Comment by esmail** [comment]
Moving this over to kobotoolbox/kpi#786.

**Comment by esmail** [comment]
@jeverling, we're already moving towards using `JSONField` in some places under Django 1.8 with the backported [HearstCorp/django-jsonbfield](https://github.com/HearstCorp/django-jsonbfield). That said, we've been reliant on Mongo for extracting data from the system, including in the KoBoCAT code being ported over, so taking it out of the process will take some adjustments.

@dorey and @ksamuel, what do you think about moving to using Postgres for this at a later date?
