### ISSUE TITLE
Adding SMTP configuration leads to 502 Bad Gateway Error

### ISSUE THREAD

**Issue by AnandMoorthy** [kobotoolbox/kobo-docker#54]
Deployed KoboToolbox with docker, and i configure the variables in /envfiles/smtp.txt. When i start to register the new user it takes me to the 502 Bad Gateway error.

My config file:
 For sending e-mail using SMTP. #

 NOTE: These and the e-mail settings from `envfiles/aws.txt` are mutually exclusive; do not use both. See https://docs.djangoproject.com/en/1.8/topics/email/#smtp-backend.
EMAIL_BACKEND= django.core.mail.backends.smtp.EmailBackend
EMAIL_HOST= 'smtp.gmail.com'
EMAIL_PORT= 587
EMAIL_HOST_USER= '*******************_'
EMAIL_HOST_PASSWORD= '**_********'
EMAIL_USE_TLS= True
# DEFAULT_FROM_EMAIL=

Is this the problem with my config or in package itself?

**Comment by esmail** [comment]
Getting 502s usually means Django is failing to start. You can get more details on the error by opening a terminal in the KPI container with `docker exec -it kobodocker_kpi_1 bash`, then executing the following and watching for errors:
```
sv stop uwsgi
python manage.py runserver
```

**Comment by grueneedv** [comment]
The Line
EMAIL_BACKEND= django.core.mail.backends.smtp.EmailBackend
must be at least changed to
EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'

**Comment by esmail** [comment]
@grueneedv, because that's a Docker Compose env. file, the literal quotation characters would be preserved (i.e. the value of the variable would literally be `'django.core.mail.backends.smtp.EmailBackend'`) and Python/Django would preserve them as well.

Example using `EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'`:
```
$ docker-compose run --rm kpi python -c 'import os; print repr(os.environ["EMAIL_BACKEND"])'
"'django.core.mail.backends.smtp.EmailBackend'"
```

**Comment by esmail** [comment]
Added a brief reference to the `env_file` documentation at https://github.com/kobotoolbox/kobo-docker/tree/master/envfiles.

**Comment by grueneedv** [comment]
My suggestion solved the problem in that way, that the filebackend is enabled again. Sorry for the wrong direction. But I'm seriousy struggled with the same problem.
The solution is how I entered the data. Instead of entering EMAIL_HOST='mymailserver.example.com' in the envfiles/smtp.txt I entered EMAIL_HOST=mymailserver.example.com and it worked. Going to Pull that as example in the file.

**Comment by klausen12** [comment]
I have the same problem! I try to make smtp working as well! so should I put quotes or not?

**Comment by klausen12** [comment]
sorry for my english! I'm not very good

**Comment by klausen12** [comment]
oohhhh ... It works, I follow your Instruction @grueneedv
