### ISSUE TITLE
enketo-kobocat intergration

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#88]
Hi team,

I'm using kobo docker, today I updated via `docker-compose pull` and  `docker-compose up -d`
now i'm receiving an error while accessing it for web entry;

> Enketo error, reason: Forbidden. This server is not linked with Enketo.

Need your urgent attentions

**Comment by esmail** [comment]
I'm assuming this is due to the fact that your `kobo-docker` code is out of date, so please pull the latest changes and try again. I'll update the documentation to mention this. Let us know if you're still having issues.

**Comment by iahmedani** [comment]
email many thanks for your support,

I pulled via `git pull ` but still issue persists. 

Please help.

**Comment by esmail** [comment]
I was expecting this would be caused by not having [this new line of `enketo_express/config.json](https://github.com/kobotoolbox/kobo-docker/blob/0776399/enketo_express/config.json#L5); if you didn't do so after pulling the new `kobo-docker` code, please `docker-compose up -d` again.

If there's another issue, you'll want to check `/srv/src/enketo_express/config.json` inside the `enketo_express` container for the above-linked `server url` entry and to see if the `api key` entry matches what you entered for your `ENKETO_API_TOKEN` in your envfile.

**Comment by marjetika** [comment]
I had the same problem. The cause was that I changed `linked form and data server` section in `enketo_express/config.json`. That section links Enketo with the server.
