### ISSUE TITLE
Why I  can't use  --extension es6

### ISSUE THREAD

**Issue by tfgbestneal** [kobotoolbox/kobo-docker#92]
Hi Team,
I am trying to use 'python manage.py makemessages -l en -e es6' to extract the text in .es6 files to translate , in the kpi container, but It's not work,nothing exported,no .po file, what's wrong? thanks very much!

**Comment by esmail** [comment]
It doesn't work because we're not using the [necessary `gettext` functions](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#using-the-javascript-translation-catalog) in the client code and [Django's JS string extraction](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#internationalization-in-javascript-code) [doesn't work particularly well](http://nedbatchelder.com/blog/201104/a_javascript_lexer_in_python_and_the_saga_behind_it.html).

I've created a new issue, kobotoolbox/kpi#1080, to track this.
